source "https://rubygems.org"

gem "activerecord"
gem "faraday"
gem "i18n"
gem "kamal", "~> 2.3"
gem "minitest"
gem "pg"
gem "psych"
gem "rackup"
gem "rake"
gem "ruby-openai"
gem "sinatra"
gem "telegram-bot-ruby", "~> 2.0"
gem "mutex_m", "~> 0.2.0"
