common: &common
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_POOL_SIZE') { 5 } %>
  host: <%= ENV.fetch('PG_HOST') { 'localhost' } %>
  port: 5432
  timeout: 5000

development:
  <<: *common
  database: <%= ENV['BOT_NAME'] %>_development

production: &production
  <<: *common
  database: <%= ENV['BOT_NAME'] %>_production
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
